2025-10-14 04:05:58.547776+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 13:56:49.779373+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 13:59:49.391767+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 13:59:50.513309+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 13:59:56.806834+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:02:58.345137+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:03:18.792644+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:04:12.528348+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:04:12.529390+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:04:13.637044+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:04:34.567197+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:04:34.569201+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:04:34.574259+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:04:35.262620+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:04:47.342522+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:16:07.443645+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:16:07.449003+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:16:07.461269+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:16:08.091964+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:16:18.270273+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 14:34:03.416658+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "abonos_compras" ya existe
Table "abonos_compras" already exists; SQL statement:
CREATE TABLE "abonos_compras" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_CTAP" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Proveedor" INT NOT NULL,
  "Fecha" VARCHAR(255) NOT NULL,
  "Monto" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:34:03.419659+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "abonos_ventas" ya existe
Table "abonos_ventas" already exists; SQL statement:
CREATE TABLE "abonos_ventas" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_CTAC" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Cliente" INT NOT NULL,
  "Fecha" VARCHAR(255) NOT NULL,
  "Monto" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:34:03.421653+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "actividades" ya existe
Table "actividades" already exists; SQL statement:
CREATE TABLE "actividades" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Descripcion" VARCHAR(1000),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.422654+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "categorias" ya existe
Table "categorias" already exists; SQL statement:
CREATE TABLE "categorias" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Nombre" VARCHAR(150),
  "Descripcion" VARCHAR(1000),
  "Imagen" BLOB,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:34:03.423696+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "clientes" ya existe
Table "clientes" already exists; SQL statement:
CREATE TABLE "clientes" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Codigo" VARCHAR(50),
  "Nombre" VARCHAR(150),
  "Telefono" VARCHAR(20),
  "Direccion" VARCHAR(1000),
  "Email" VARCHAR(150),
  "Imagen" BLOB,
  "Activo" BOOLEAN,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.424694+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "comentarios" ya existe
Table "comentarios" already exists; SQL statement:
CREATE TABLE "comentarios" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura_C" INT,
  "Secuencial_Factura_V" INT,
  "Secuencial_Producto" INT,
  "Secuencial_Cotizacion" INT,
  "Secuencial_Orden" INT,
  "Contenido" VARCHAR(1000),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.425688+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "compras" ya existe
Table "compras" already exists; SQL statement:
CREATE TABLE "compras" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Forma_Pago" VARCHAR(50),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT,
  "Documento" BLOB
) [42101-224]
2025-10-14 14:34:03.428195+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "compras_detalles" ya existe
Table "compras_detalles" already exists; SQL statement:
CREATE TABLE "compras_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura" INT,
  "Secuencial_Proveedor" INT,
  "Secuencial_Producto" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Total" DOUBLE,
  "Tipo" VARCHAR(50),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.430571+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "cotizaciones" ya existe
Table "cotizaciones" already exists; SQL statement:
CREATE TABLE "cotizaciones" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cliente" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.432621+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "cotizaciones_detalles" ya existe
Table "cotizaciones_detalles" already exists; SQL statement:
CREATE TABLE "cotizaciones_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cotizacion" INT,
  "Secuencial_Usuario" INT,
  "Secuencial_Cliente" INT,
  "Secuencial_Producto" INT,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Tipo" VARCHAR(50),
  "Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.434636+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "kardex" ya existe
Table "kardex" already exists; SQL statement:
CREATE TABLE "kardex" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Fecha" VARCHAR(255) NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Descripcion" VARCHAR(1000) NOT NULL,
  "Cantidad" DOUBLE NOT NULL,
  "Costo" DOUBLE NOT NULL,
  "Costo_Total" DOUBLE NOT NULL,
  "Venta" DOUBLE NOT NULL,
  "Venta_Total" DOUBLE NOT NULL,
  "Saldo" DOUBLE NOT NULL,
  "Movimiento" VARCHAR(50) NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:34:03.435632+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ordenes" ya existe
Table "ordenes" already exists; SQL statement:
CREATE TABLE "ordenes" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.437621+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ordenes_detalles" ya existe
Table "ordenes_detalles" already exists; SQL statement:
CREATE TABLE "ordenes_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Orden" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Proveedor" INT NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Tipo" VARCHAR(50),
  "Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.438691+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "productos" ya existe
Table "productos" already exists; SQL statement:
CREATE TABLE "productos" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT NOT NULL,
  "Codigo" VARCHAR(50) NOT NULL,
  "Descripcion" VARCHAR(1000) NOT NULL,
  "Cantidad" DOUBLE NOT NULL,
  "Precio_Costo" DOUBLE NOT NULL,
  "Precio_Venta" DOUBLE NOT NULL,
  "Marca" VARCHAR(100),
  "Codigo_Barra" VARCHAR(50),
  "Codigo_Fabricante" VARCHAR(50),
  "Imagen" BLOB,
  "Fecha_Caducidad" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Secuencial_Categoria" INT NOT NULL,
  "Expira" BOOLEAN NOT NULL,
  "Existencia_Minima" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:34:03.441127+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "proveedores" ya existe
Table "proveedores" already exists; SQL statement:
CREATE TABLE "proveedores" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Nombre" VARCHAR(150),
  "Telefono" VARCHAR(20),
  "Direccion" VARCHAR(1000),
  "Email" VARCHAR(150),
  "Contacto" VARCHAR(100),
  "Tipo" VARCHAR(50),
  "Imagen" BLOB,
  "Activo" BOOLEAN,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:34:03.442339+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "usuarios" ya existe
Table "usuarios" already exists; SQL statement:
CREATE TABLE "usuarios" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Codigo" VARCHAR(50) NOT NULL,
  "Nombre" VARCHAR(150),
  "Password" VARCHAR(255) NOT NULL,
  "Imagen" BLOB,
  "Acceso" VARCHAR(50) NOT NULL,
  "Activo" BOOLEAN NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:34:03.444362+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ventas" ya existe
Table "ventas" already exists; SQL statement:
CREATE TABLE "ventas" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cliente" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Forma_Pago" VARCHAR(50),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT,
  "Documento" BLOB
) [42101-224]
2025-10-14 14:34:03.447363+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ventas_detalles" ya existe
Table "ventas_detalles" already exists; SQL statement:
CREATE TABLE "ventas_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura" INT NOT NULL,
  "Secuencial_Cliente" INT NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Total" DOUBLE,
  "Tipo" VARCHAR(50),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.444395+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "abonos_compras" ya existe
Table "abonos_compras" already exists; SQL statement:
CREATE TABLE "abonos_compras" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_CTAP" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Proveedor" INT NOT NULL,
  "Fecha" VARCHAR(255) NOT NULL,
  "Monto" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:41:55.447914+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "abonos_ventas" ya existe
Table "abonos_ventas" already exists; SQL statement:
CREATE TABLE "abonos_ventas" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_CTAC" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Cliente" INT NOT NULL,
  "Fecha" VARCHAR(255) NOT NULL,
  "Monto" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:41:55.449044+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "actividades" ya existe
Table "actividades" already exists; SQL statement:
CREATE TABLE "actividades" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Descripcion" VARCHAR(1000),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.449044+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "categorias" ya existe
Table "categorias" already exists; SQL statement:
CREATE TABLE "categorias" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Nombre" VARCHAR(150),
  "Descripcion" VARCHAR(1000),
  "Imagen" BLOB,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:41:55.450558+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "clientes" ya existe
Table "clientes" already exists; SQL statement:
CREATE TABLE "clientes" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Codigo" VARCHAR(50),
  "Nombre" VARCHAR(150),
  "Telefono" VARCHAR(20),
  "Direccion" VARCHAR(1000),
  "Email" VARCHAR(150),
  "Imagen" BLOB,
  "Activo" BOOLEAN,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.452035+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "comentarios" ya existe
Table "comentarios" already exists; SQL statement:
CREATE TABLE "comentarios" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura_C" INT,
  "Secuencial_Factura_V" INT,
  "Secuencial_Producto" INT,
  "Secuencial_Cotizacion" INT,
  "Secuencial_Orden" INT,
  "Contenido" VARCHAR(1000),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.453030+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "compras" ya existe
Table "compras" already exists; SQL statement:
CREATE TABLE "compras" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Forma_Pago" VARCHAR(50),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT,
  "Documento" BLOB
) [42101-224]
2025-10-14 14:41:55.455026+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "compras_detalles" ya existe
Table "compras_detalles" already exists; SQL statement:
CREATE TABLE "compras_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura" INT,
  "Secuencial_Proveedor" INT,
  "Secuencial_Producto" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Total" DOUBLE,
  "Tipo" VARCHAR(50),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.457074+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "cotizaciones" ya existe
Table "cotizaciones" already exists; SQL statement:
CREATE TABLE "cotizaciones" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cliente" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.459399+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "cotizaciones_detalles" ya existe
Table "cotizaciones_detalles" already exists; SQL statement:
CREATE TABLE "cotizaciones_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cotizacion" INT,
  "Secuencial_Usuario" INT,
  "Secuencial_Cliente" INT,
  "Secuencial_Producto" INT,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Tipo" VARCHAR(50),
  "Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.461402+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "kardex" ya existe
Table "kardex" already exists; SQL statement:
CREATE TABLE "kardex" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Fecha" VARCHAR(255) NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Descripcion" VARCHAR(1000) NOT NULL,
  "Cantidad" DOUBLE NOT NULL,
  "Costo" DOUBLE NOT NULL,
  "Costo_Total" DOUBLE NOT NULL,
  "Venta" DOUBLE NOT NULL,
  "Venta_Total" DOUBLE NOT NULL,
  "Saldo" DOUBLE NOT NULL,
  "Movimiento" VARCHAR(50) NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:41:55.463399+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ordenes" ya existe
Table "ordenes" already exists; SQL statement:
CREATE TABLE "ordenes" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.465400+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ordenes_detalles" ya existe
Table "ordenes_detalles" already exists; SQL statement:
CREATE TABLE "ordenes_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Orden" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Proveedor" INT NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Tipo" VARCHAR(50),
  "Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.466876+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "productos" ya existe
Table "productos" already exists; SQL statement:
CREATE TABLE "productos" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT NOT NULL,
  "Codigo" VARCHAR(50) NOT NULL,
  "Descripcion" VARCHAR(1000) NOT NULL,
  "Cantidad" DOUBLE NOT NULL,
  "Precio_Costo" DOUBLE NOT NULL,
  "Precio_Venta" DOUBLE NOT NULL,
  "Marca" VARCHAR(100),
  "Codigo_Barra" VARCHAR(50),
  "Codigo_Fabricante" VARCHAR(50),
  "Imagen" BLOB,
  "Fecha_Caducidad" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Secuencial_Categoria" INT NOT NULL,
  "Expira" BOOLEAN NOT NULL,
  "Existencia_Minima" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:41:55.469456+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "proveedores" ya existe
Table "proveedores" already exists; SQL statement:
CREATE TABLE "proveedores" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Nombre" VARCHAR(150),
  "Telefono" VARCHAR(20),
  "Direccion" VARCHAR(1000),
  "Email" VARCHAR(150),
  "Contacto" VARCHAR(100),
  "Tipo" VARCHAR(50),
  "Imagen" BLOB,
  "Activo" BOOLEAN,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 14:41:55.470473+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "usuarios" ya existe
Table "usuarios" already exists; SQL statement:
CREATE TABLE "usuarios" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Codigo" VARCHAR(50) NOT NULL,
  "Nombre" VARCHAR(150),
  "Password" VARCHAR(255) NOT NULL,
  "Imagen" BLOB,
  "Acceso" VARCHAR(50) NOT NULL,
  "Activo" BOOLEAN NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-14 14:41:55.471472+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ventas" ya existe
Table "ventas" already exists; SQL statement:
CREATE TABLE "ventas" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cliente" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Forma_Pago" VARCHAR(50),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT,
  "Documento" BLOB
) [42101-224]
2025-10-14 14:41:55.473475+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ventas_detalles" ya existe
Table "ventas_detalles" already exists; SQL statement:
CREATE TABLE "ventas_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura" INT NOT NULL,
  "Secuencial_Cliente" INT NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Total" DOUBLE,
  "Tipo" VARCHAR(50),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-14 20:20:19.591421+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 20:20:24.105523+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 20:27:34.475599+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:40)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:499)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:372)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:550)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:102)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:82)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:395)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:262)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:45)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:223)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:170)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1432)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1503)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:55)
	at com.monituxpos.Clases.MonituxDBContext.init(MonituxDBContext.java:56)
	at com.monituxpos.Ventanas.V_Login.<init>(V_Login.java:56)
	at com.monituxpos.Ventanas.V_Login.lambda$main$0(V_Login.java:689)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:702)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 52 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 46 more
2025-10-14 20:28:09.316389+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:40)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:499)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:372)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:550)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:102)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:82)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:395)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:262)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:45)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:223)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:170)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1432)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1503)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:55)
	at com.monituxpos.Clases.MonituxDBContext.init(MonituxDBContext.java:56)
	at com.monituxpos.Ventanas.V_Login.<init>(V_Login.java:56)
	at com.monituxpos.Ventanas.V_Login.lambda$main$0(V_Login.java:689)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:702)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 52 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 46 more
2025-10-14 20:28:49.216608+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:40)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:499)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:372)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:550)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:102)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:82)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:395)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:262)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:45)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:223)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:170)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1432)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1503)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:55)
	at com.monituxpos.Clases.MonituxDBContext.init(MonituxDBContext.java:56)
	at com.monituxpos.Ventanas.V_Login.<init>(V_Login.java:56)
	at com.monituxpos.Ventanas.V_Login.lambda$main$0(V_Login.java:689)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:702)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 52 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 46 more
2025-10-14 20:32:50.292447+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 20:32:53.409151+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 20:33:53.199505+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 20:33:55.988499+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 20:49:29.867213+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 20:49:41.160655+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 21:47:31.584108+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 21:52:44.795960+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 21:54:15.536285+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]" [50000-240]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1675)
	at org.h2.mvstore.MVStore.panic(MVStore.java:502)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:296)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2164)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:328)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:350)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:291)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1038)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]" [50000-240]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	... 16 more
2025-10-14 21:54:18.437161+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]" [50000-240]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1675)
	at org.h2.mvstore.MVStore.panic(MVStore.java:502)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:296)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2164)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:328)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:350)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:291)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1038)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]" [50000-240]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	... 16 more
2025-10-14 22:00:52.600244+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:40)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:499)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:372)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:550)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:102)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:82)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:395)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:262)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:45)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:223)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:170)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1432)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1503)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:55)
	at com.monituxpos.Clases.MonituxDBContext.init(MonituxDBContext.java:56)
	at com.monituxpos.Ventanas.V_Login.<init>(V_Login.java:60)
	at com.monituxpos.Ventanas.V_Login.lambda$main$0(V_Login.java:761)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:702)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 52 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 46 more
2025-10-14 22:54:40.037012+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 22:54:41.946131+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-14 23:11:23.871365+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]" [50000-240]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1675)
	at org.h2.mvstore.MVStore.panic(MVStore.java:502)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:296)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2164)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:328)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:350)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:291)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1038)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]" [50000-240]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 22 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.4.240/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	... 16 more
2025-10-14 23:14:32.463591+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USUARIOS" not found (candidates are: "usuarios"); SQL statement:
SELECT * FROM usuarios
WHERE "Codigo" = 'el_codigo_que_usaste'
  AND "Password" = 'D8GT3eN2bYJL0k/UZDGO6Q=='
  AND "Secuencial_Empresa" = el_valor_usado
  AND "Activo" = true [42103-240]
2025-10-14 23:15:03.231127+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USUARIOS" not found (candidates are: "usuarios"); SQL statement:
SELECT * FROM usuarios
WHERE "Codigo" = '4444'
  AND "Password" = 'D8GT3eN2bYJL0k/UZDGO6Q=='
  AND "Secuencial_Empresa" = el_valor_usado
  AND "Activo" = true [42103-240]
2025-10-14 23:15:14.662395+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USUARIOS" not found (candidates are: "usuarios"); SQL statement:
SELECT * FROM usuarios
WHERE "Codigo" = '4444'
  AND "Password" = 'D8GT3eN2bYJL0k/UZDGO6Q=='
  AND "Secuencial_Empresa" = 1
  AND "Activo" = true [42103-240]
2025-10-14 23:15:22.533063+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USUARIOS" not found (candidates are: "usuarios"); SQL statement:
SELECT * FROM usuarios
WHERE "Codigo" = '4444'
  AND "Password" = 'D8GT3eN2bYJL0k/UZDGO6Q=='
  AND "Secuencial_Empresa" = 1
  AND "Activo" = 0 [42103-240]
2025-10-14 23:15:29.055691+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USUARIOS" not found (candidates are: "usuarios"); SQL statement:
SELECT * FROM usuarios
WHERE "Codigo" = '4444'
  AND "Password" = 'D8GT3eN2bYJL0k/UZDGO6Q=='
  AND "Secuencial_Empresa" = 1
  AND "Activo" = false [42103-240]
2025-10-14 23:22:51.687371+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:40)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:499)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:372)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:550)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:102)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:82)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:395)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:262)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:45)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:223)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:170)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1432)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1503)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:55)
	at com.monituxpos.Clases.MonituxDBContext.init(MonituxDBContext.java:56)
	at com.monituxpos.Ventanas.V_Login.<init>(V_Login.java:60)
	at com.monituxpos.Ventanas.V_Login.lambda$main$0(V_Login.java:749)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:702)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 52 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 46 more
2025-10-15 20:52:15.559629+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-15 20:59:40.152090+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya está cerrado
The object is already closed [90007-224]
2025-10-15 21:23:08.656599+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "Empresa" no encontrada
Table "Empresa" not found; SQL statement:
select e1_0."Secuencial",e1_0."Activa",e1_0."Direccion",e1_0."Email",e1_0."ISV",e1_0."Imagen",e1_0."Moneda",e1_0."Nombre",e1_0."RSS",e1_0."Secuencial_Usuario",e1_0."Telefono" from "Empresa" e1_0 where e1_0."Activa"=true [42102-224]
