2025-10-17 18:49:38.309105+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-17 18:49:39.836794+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-17 18:50:07.751352+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-17 18:50:09.241646+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:08:25.431698+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "abonos_compras" ya existe
Table "abonos_compras" already exists; SQL statement:
CREATE TABLE "abonos_compras" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_CTAP" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Proveedor" INT NOT NULL,
  "Fecha" VARCHAR(255) NOT NULL,
  "Monto" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-18 02:08:25.438154+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "abonos_ventas" ya existe
Table "abonos_ventas" already exists; SQL statement:
CREATE TABLE "abonos_ventas" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_CTAC" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Cliente" INT NOT NULL,
  "Fecha" VARCHAR(255) NOT NULL,
  "Monto" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-18 02:08:25.439154+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "actividades" ya existe
Table "actividades" already exists; SQL statement:
CREATE TABLE "actividades" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Descripcion" VARCHAR(1000),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.441152+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "categorias" ya existe
Table "categorias" already exists; SQL statement:
CREATE TABLE "categorias" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Nombre" VARCHAR(150),
  "Descripcion" VARCHAR(1000),
  "Imagen" BLOB,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-18 02:08:25.442151+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "clientes" ya existe
Table "clientes" already exists; SQL statement:
CREATE TABLE "clientes" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Codigo" VARCHAR(50),
  "Nombre" VARCHAR(150),
  "Telefono" VARCHAR(20),
  "Direccion" VARCHAR(1000),
  "Email" VARCHAR(150),
  "Imagen" BLOB,
  "Activo" BOOLEAN,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.443151+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "comentarios" ya existe
Table "comentarios" already exists; SQL statement:
CREATE TABLE "comentarios" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura_C" INT,
  "Secuencial_Factura_V" INT,
  "Secuencial_Producto" INT,
  "Secuencial_Cotizacion" INT,
  "Secuencial_Orden" INT,
  "Contenido" VARCHAR(1000),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.446152+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "compras" ya existe
Table "compras" already exists; SQL statement:
CREATE TABLE "compras" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Forma_Pago" VARCHAR(50),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT,
  "Documento" BLOB
) [42101-224]
2025-10-18 02:08:25.448150+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "compras_detalles" ya existe
Table "compras_detalles" already exists; SQL statement:
CREATE TABLE "compras_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura" INT,
  "Secuencial_Proveedor" INT,
  "Secuencial_Producto" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Total" DOUBLE,
  "Tipo" VARCHAR(50),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.450150+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "cotizaciones" ya existe
Table "cotizaciones" already exists; SQL statement:
CREATE TABLE "cotizaciones" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cliente" INT,
  "Secuencial_Usuario" INT,
  "Fecha" VARCHAR(255),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.451394+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "cotizaciones_detalles" ya existe
Table "cotizaciones_detalles" already exists; SQL statement:
CREATE TABLE "cotizaciones_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cotizacion" INT,
  "Secuencial_Usuario" INT,
  "Secuencial_Cliente" INT,
  "Secuencial_Producto" INT,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Tipo" VARCHAR(50),
  "Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.453472+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "kardex" ya existe
Table "kardex" already exists; SQL statement:
CREATE TABLE "kardex" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Fecha" VARCHAR(255) NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Descripcion" VARCHAR(1000) NOT NULL,
  "Cantidad" DOUBLE NOT NULL,
  "Costo" DOUBLE NOT NULL,
  "Costo_Total" DOUBLE NOT NULL,
  "Venta" DOUBLE NOT NULL,
  "Venta_Total" DOUBLE NOT NULL,
  "Saldo" DOUBLE NOT NULL,
  "Movimiento" VARCHAR(50) NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-18 02:08:25.456474+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ordenes" ya existe
Table "ordenes" already exists; SQL statement:
CREATE TABLE "ordenes" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.458472+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ordenes_detalles" ya existe
Table "ordenes_detalles" already exists; SQL statement:
CREATE TABLE "ordenes_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Orden" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Secuencial_Proveedor" INT NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Tipo" VARCHAR(50),
  "Total" DOUBLE,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.460473+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "productos" ya existe
Table "productos" already exists; SQL statement:
CREATE TABLE "productos" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Proveedor" INT NOT NULL,
  "Codigo" VARCHAR(50) NOT NULL,
  "Descripcion" VARCHAR(1000) NOT NULL,
  "Cantidad" DOUBLE NOT NULL,
  "Precio_Costo" DOUBLE NOT NULL,
  "Precio_Venta" DOUBLE NOT NULL,
  "Marca" VARCHAR(100),
  "Codigo_Barra" VARCHAR(50),
  "Codigo_Fabricante" VARCHAR(50),
  "Imagen" BLOB,
  "Fecha_Caducidad" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Secuencial_Categoria" INT NOT NULL,
  "Expira" BOOLEAN NOT NULL,
  "Existencia_Minima" DOUBLE NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-18 02:08:25.462475+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "proveedores" ya existe
Table "proveedores" already exists; SQL statement:
CREATE TABLE "proveedores" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Nombre" VARCHAR(150),
  "Telefono" VARCHAR(20),
  "Direccion" VARCHAR(1000),
  "Email" VARCHAR(150),
  "Contacto" VARCHAR(100),
  "Tipo" VARCHAR(50),
  "Imagen" BLOB,
  "Activo" BOOLEAN,
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:08:25.464477+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "usuarios" ya existe
Table "usuarios" already exists; SQL statement:
CREATE TABLE "usuarios" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Codigo" VARCHAR(50) NOT NULL,
  "Nombre" VARCHAR(150),
  "Password" VARCHAR(255) NOT NULL,
  "Imagen" BLOB,
  "Acceso" VARCHAR(50) NOT NULL,
  "Activo" BOOLEAN NOT NULL,
  "Secuencial_Empresa" INT NOT NULL
) [42101-224]
2025-10-18 02:08:25.464477+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ventas" ya existe
Table "ventas" already exists; SQL statement:
CREATE TABLE "ventas" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Cliente" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Tipo" VARCHAR(50),
  "Forma_Pago" VARCHAR(50),
  "Total" DOUBLE,
  "Otros_Cargos" DOUBLE,
  "Descuento" DOUBLE,
  "Impuesto" DOUBLE,
  "Gran_Total" DOUBLE,
  "Secuencial_Empresa" INT,
  "Documento" BLOB
) [42101-224]
2025-10-18 02:08:25.466477+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "ventas_detalles" ya existe
Table "ventas_detalles" already exists; SQL statement:
CREATE TABLE "ventas_detalles" (
  "Secuencial" INT AUTO_INCREMENT PRIMARY KEY,
  "Secuencial_Factura" INT NOT NULL,
  "Secuencial_Cliente" INT NOT NULL,
  "Secuencial_Producto" INT NOT NULL,
  "Secuencial_Usuario" INT NOT NULL,
  "Fecha" VARCHAR(255),
  "Codigo" VARCHAR(25),
  "Descripcion" VARCHAR(1000),
  "Cantidad" DOUBLE,
  "Precio" DOUBLE,
  "Total" DOUBLE,
  "Tipo" VARCHAR(50),
  "Secuencial_Empresa" INT
) [42101-224]
2025-10-18 02:50:28.822948+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "abonos_compras" not found (this database is empty); SQL statement:
TRUNCATE TABLE "abonos_compras" [42104-224]
2025-10-18 02:50:28.828419+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "abonos_ventas" not found (this database is empty); SQL statement:
TRUNCATE TABLE "abonos_ventas" [42104-224]
2025-10-18 02:50:28.829441+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "actividades" not found (this database is empty); SQL statement:
TRUNCATE TABLE "actividades" [42104-224]
2025-10-18 02:50:28.830953+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "categorias" not found (this database is empty); SQL statement:
TRUNCATE TABLE "categorias" [42104-224]
2025-10-18 02:50:28.832065+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "clientes" not found (this database is empty); SQL statement:
TRUNCATE TABLE "clientes" [42104-224]
2025-10-18 02:50:28.833087+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "comentarios" not found (this database is empty); SQL statement:
TRUNCATE TABLE "comentarios" [42104-224]
2025-10-18 02:50:28.833087+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "compras" not found (this database is empty); SQL statement:
TRUNCATE TABLE "compras" [42104-224]
2025-10-18 02:50:28.835102+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "compras_detalles" not found (this database is empty); SQL statement:
TRUNCATE TABLE "compras_detalles" [42104-224]
2025-10-18 02:50:28.837092+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "cotizaciones" not found (this database is empty); SQL statement:
TRUNCATE TABLE "cotizaciones" [42104-224]
2025-10-18 02:50:28.839090+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "cotizaciones_detalles" not found (this database is empty); SQL statement:
TRUNCATE TABLE "cotizaciones_detalles" [42104-224]
2025-10-18 02:50:28.841406+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "kardex" not found (this database is empty); SQL statement:
TRUNCATE TABLE "kardex" [42104-224]
2025-10-18 02:50:28.843538+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "ordenes" not found (this database is empty); SQL statement:
TRUNCATE TABLE "ordenes" [42104-224]
2025-10-18 02:50:28.845546+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "ordenes_detalles" not found (this database is empty); SQL statement:
TRUNCATE TABLE "ordenes_detalles" [42104-224]
2025-10-18 02:50:28.845546+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "productos" not found (this database is empty); SQL statement:
TRUNCATE TABLE "productos" [42104-224]
2025-10-18 02:50:28.847538+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "proveedores" not found (this database is empty); SQL statement:
TRUNCATE TABLE "proveedores" [42104-224]
2025-10-18 02:50:28.849548+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "usuarios" not found (this database is empty); SQL statement:
TRUNCATE TABLE "usuarios" [42104-224]
2025-10-18 02:50:28.850677+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "ventas" not found (this database is empty); SQL statement:
TRUNCATE TABLE "ventas" [42104-224]
2025-10-18 02:50:28.852675+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "ventas_detalles" not found (this database is empty); SQL statement:
TRUNCATE TABLE "ventas_detalles" [42104-224]
2025-10-18 02:50:28.855837+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "cuentas_cobrar" not found (this database is empty); SQL statement:
TRUNCATE TABLE "cuentas_cobrar" [42104-224]
2025-10-18 02:50:28.857864+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "cuentas_pagar" not found (this database is empty); SQL statement:
TRUNCATE TABLE "cuentas_pagar" [42104-224]
2025-10-18 02:50:28.857864+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "empresas" not found (this database is empty); SQL statement:
TRUNCATE TABLE "empresas" [42104-224]
2025-10-18 02:50:28.858856+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "ingresos" not found (this database is empty); SQL statement:
TRUNCATE TABLE "ingresos" [42104-224]
2025-10-18 02:50:28.859859+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "egresos" not found (this database is empty); SQL statement:
TRUNCATE TABLE "egresos" [42104-224]
2025-10-18 02:51:36.331439+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:51:38.280451+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:51:59.959808+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:52:01.750086+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:52:27.550256+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:52:28.530354+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:52:47.663221+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:52:48.652056+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:53:15.705594+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:53:15.722356+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:53:36.809888+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:53:36.811887+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:53:36.814884+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:53:37.470707+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:53:47.810693+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:54:19.944681+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:54:21.109736+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:54:36.070327+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 02:55:15.467445+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 03:08:23.990692+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 03:08:25.381805+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 13:12:11.227188+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 13:12:12.769485+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 13:12:46.406541+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 13:12:47.700029+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 13:54:40.124518+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 13:54:41.355885+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 16:30:36.529559+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 16:30:37.628402+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 16:31:26.226670+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 16:31:27.114912+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 17:14:26.257054+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLDataException: Valor demasiado largo para la columna "Imagen BINARY VARYING(255)": "X'ffd8ffe000104a46494600010200000100010000ffdb0043000101010101010101010101010101... (11996)"
Value too long for column "Imagen BINARY VARYING(255)": "X'ffd8ffe000104a46494600010200000100010000ffdb0043000101010101010101010101010101... (11996)"; SQL statement:
insert into "empresas" ("Activa","Direccion","Email","ISV","Imagen","Moneda","Nombre","RSS","Secuencial_Usuario","Telefono","Secuencial") values (?,?,?,?,?,?,?,?,?,?,default) [22001-224]
2025-10-18 17:26:19.000340+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 17:26:21.290964+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 17:36:59.373892+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:40)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:499)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:372)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:550)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:102)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:82)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:395)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:262)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:45)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:223)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:170)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:129)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:449)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:101)
	at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:210)
	at com.monituxpos.Clases.MonituxDBContext.init(MonituxDBContext.java:215)
	at com.monituxpos.Ventanas.V_Login.<init>(V_Login.java:54)
	at com.monituxpos.Main.lambda$main$0(Main.java:24)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:702)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 53 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/Miguel Cerrato/Documents/NetBeansProjects/Monitux-POS-Java/Resources/Database/H2-DB.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 47 more
2025-10-18 17:41:55.173342+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 17:41:56.976833+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 17:46:58.847224+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 17:47:00.261666+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 17:47:22.789430+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 17:47:23.980906+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 22:33:50.519728+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 22:33:51.712332+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 22:34:11.141071+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 22:34:12.303304+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 23:52:49.049528+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 23:52:50.664647+02:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 23:53:07.702207+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
2025-10-18 23:53:08.735694+02:00 jdbc[5]: exception
org.h2.jdbc.JdbcSQLNonTransientException: El objeto ya est치 cerrado
The object is already closed [90007-224]
